version: "3.9"

services:
  api:
    #build: .
    image: collectoryx-api
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      SPRING_APPLICATION_JSON: '{"spring":{"datasource":{"url":"jdbc:mariadb://mariadb:3306/collectoryx", "username": "root", "password": "root-password"}}}'

  front:
    #build: .
    image: collectoryx-front
    ports:
      - "8082:8082"
    depends_on:
      - api
    volumes:
      - images:/
      - ./public:/usr/src/app/public


  mariadb:
    image: "mariadb:10.9"
    ports:
      - "33306:3306"
    environment:
      MARIADB_USER: collectoryx
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: root-password
      MARIADB_DATABASE: collectoryx

volumes:
  - images:

