version: "3.9"

services:
  api:
    #build: .
    image: lopiv2/collectoryx-api:1.0.1
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    volumes:
      - uploads:/app/uploads:rw
    environment:
      SPRING_APPLICATION_JSON: '{"spring":{"datasource":{"url":"jdbc:mariadb://mariadb:3306/collectoryx", "username": "root", "password": "root-password"}},"collectoryx.upload-directory":"/app/uploads/"}'

  front:
    #build: .
    image: lopiv2/collectoryx-front:1.0.1
    ports:
      - "8082:80"
    depends_on:
      - api
    volumes:
      - uploads:/app/public/images/uploads:ro


  mariadb:
    image: "mariadb:10.9"
    ports:
      - "33306:3306"
    environment:
      MARIADB_USER: collectoryx
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: root-password
      MARIADB_DATABASE: collectoryx

volumes:
  uploads:

