version: "3.9"

services:
  api:
    build:
      context: ./
    image: lopiv2/collectoryx-api:latest
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    container_name: collectoryx-api
    volumes:
      - uploads:/app/uploads:rw
    environment:
      SPRING_APPLICATION_JSON: '{"spring":{"datasource":{"url":"jdbc:mariadb://mariadb:3306/collectoryx", "username": "root", "password": "root-password"}},"collectoryx.upload-directory":"/app/uploads/"}'
    networks:
      - frontend

  front:
    image: lopiv2/collectoryx-front:latest
    build:
      context: ../collectoryx_v2_front
      args:
        - REACT_APP_API_URL=http://api.collectoryx:8080
    ports:
      - "8082:80"
    depends_on:
      - api
    volumes:
      - uploads:/app/public/images/uploads:ro
    container_name: collectoryx-front
    networks:
      - frontend

  mariadb:
    image: "mariadb:10.9"
    ports:
      - "33306:3306"
    environment:
      MARIADB_USER: collectoryx
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: root-password
      MARIADB_DATABASE: collectoryx
    networks:
      - frontend

volumes:
  uploads:

networks:
  frontend:

